### ISSUE TITLE
All Followers

### ISSUE THREAD

**Issue by respektive-reen** [mkearney/trumptweets#2]
Dear all,

during the last days I tried to download all Followers of Donald Trump (@realDonaldTrump). It worked fine with the following code: 

`## All Followers
trump<- lookup_users("realDonaldTrump")

#ALL FOLLOWERS until limit is reached
trumpflw <- get_followers("realDonaldTrump", n = trump$followers_count, retryonratelimit = TRUE)
`
**BUT** after reaching ~30 Mio. Followers the script stopped for unknown reasons and R didn't saved the downloaded Followers in "trumpflw" or anywhere else :( Does anybody know how to fix this problem, or how to create a constantly updated datafile during the download process? I don't want to run my computer another week to download all of his followers without any results.

Thanks in advance,
René

**Comment by mkearney** [comment]
@renegro90 This has been fixed in the most recent version of rtweet (install from github). for reference: https://github.com/mkearney/rtweet/issues/168
